@TranslatorApi_HostAddress = http://localhost:5170

POST {{TranslatorApi_HostAddress}}/api/Translation
Content-Type: application/json

{
  
   "text": "Bonjour",
  "sourceLanguage": "fr",
  "targetLanguage": "es"

}